on:
  schedule:
    # - cron: "0 0,6,12,18 * * *"
    - cron: "*/30 * * * *"
    # - cron: "0 0 * * *"

jobs:
  generate-data:
    runs-on: macos-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: latest

      - name: Install dependencies
        run: |
          install.packages("remotes")
          install.packages("RSelenium")
          install.packages("rvest")
          install.packages("lubridate")
          install.packages("readr")
        shell: Rscript {0}
          
      - name: Generate data
        run: Rscript R/job.R
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "GH Actions: add data"
          git push 

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
